language: go
go:
- 1.9
install:
- go get -t ./...
- make install-linters
services:
- mysql
addons:
  apt:
    sources:
    - mysql-5.7-trusty
    packages:
    - mysql-server
    - mysql-client
dist: trusty
sudo: required
script:
- make check
notifications:
  slack:
    secure: jqXilsmGqlZKk9ocTdEkkaQxj6TCVZ0yZ4itQwGhv1/2cVoLjWnVQfzULLoH6ExdTnV4htp0qr/i+qTCiMNAQyk5zaKn3+X6TWKBnHECmEVF28MklCFK+rXlFyRUA7J5cyTNgknNt6U9LJC/W759BnsDC5Rf1FXbqpBT38YuHmAD4tmhfbO5NTrR5OcYTVOQj8NaCKd+1rPZorfqwoH7YdhGTO4p3NjZFSaQLJcOhhbSxKZsJyALDshwFKSkGpycYr/ehcY80alLoZF1uvuRUARaJ0lM1CbIlpf0c9jimp++8A2aDbJjwj24+C7Z915CzbH72Tqu9t/XZFw5e0pKtwNriovjb9MvXhPP3bCYP7VG23jCzhfFv4ap9/KDPJMPmY2yiAYTrf1YWRxakyHEFfDKAVZ2qv2nZj3QlJRl8gS1BaCraQZ7ged+m1nVbeSUx5bljQC+DdEWOLAWbY9cpKx8qs6gnr+XA3YA925a7QRApU5R/6D7Lt6TFVq4uiUc8rk+EJqgOuM3n+4Go3iWIzaBm2YNUB87TSD8dhjafoqhPnfT5I1oKm/EbuQLhxDOJnqIbDhxhI/+Jt9P9CbvbjodvNAXJGAUTFbAwy7/NvC8O/iNZNQPchRy7qJC0s4Udek+S0bmPSiqwyn4H6NBU7yErFGMRxh1IunAqPunAwk=
before_install:
- openssl aes-256-cbc -K $encrypted_e3d1e333f63b_key -iv $encrypted_e3d1e333f63b_iv
  -in ./.travis/id_rsa.getsky.deploy.enc -out ./.travis/id_rsa.getsky.deploy -d
- sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('root')
  where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
- sudo mysql_upgrade --password=root
- sudo service mysql restart
- sudo mysql --password=root -e 'CREATE DATABASE IF NOT EXISTS getskytrade;'
after_success:
- sh .travis/deploy.sh
