START TRANSACTION;

ALTER TABLE Currencies 
ADD Id INT UNSIGNED NOT NULL AUTO_INCREMENT, ADD PRIMARY KEY (Id),
ADD UNIQUE INDEX CurrencyCode_UNIQUE (CurrencyCode ASC);

ALTER TABLE Countries
ADD COLUMN Id INT NOT NULL AUTO_INCREMENT,
DROP PRIMARY KEY,
ADD PRIMARY KEY (Id),
ADD UNIQUE INDEX Code_UNIQUE (Code ASC);

ALTER TABLE States 
DROP PRIMARY KEY,
ADD Id INT UNSIGNED NOT NULL AUTO_INCREMENT, ADD PRIMARY KEY (Id),
ADD UNIQUE INDEX StatesCode_UNIQUE (Code ASC);

COMMIT;
