START TRANSACTION;

ALTER TABLE Currencies
DROP COLUMN Id,
DROP INDEX CurrencyCode_UNIQUE,
ADD PRIMARY KEY (CurrencyCode);

ALTER TABLE Countries
DROP COLUMN Id,
DROP PRIMARY KEY,
DROP INDEX Code_UNIQUE,
ADD PRIMARY KEY (Code);

ALTER TABLE States
DROP COLUMN Id,
DROP PRIMARY KEY,
DROP INDEX StatesCode_UNIQUE,
ADD PRIMARY KEY (Code);

COMMIT;
